# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Co-Design: Collaborative Pedagogy in DH and Building Inclusive Digital Ethics"
author: Anita Say Chan, ed.
author_link: http://hybrid.pub/codesign
author_description: > 
  Mike Atienza, Gabe McCoy, elizaBeth Simpson, Fabian Prieto-Ñañez, Hong-An Wu, 
  Jessica Landau, Edward Prutzer, Svetlozara Stoytcheva, Melissa Seifert 
email: robin@hybridpedagogy.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring the dynamically discursive nature of syllabi as boundary objects — the 
  complex, often surprisingly fraught negotiations involved when one new element is 
  introduced to traditional syllabi: the charge to bring in a collaborator from 
  outside one's home discipline.
baseurl: "/codesign" # the subpath of your site, e.g. /blog
url: "http://hybrid.pub/" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
